# Generated by Django 3.2.13 on 2022-06-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='roler',
            field=models.CharField(choices=[('roler1', 'Contractor management'), ('roler2', 'General contractor'), ('roler3', 'Group management'), ('roler4', 'Group in general'), ('roler5', 'User')], default='roler5', max_length=30),
        ),
    ]
